ENV

diff --git a/_include b/_include
--- a/_include
+++ b/_include
@@ -58,8 +58,8 @@ function readVar {
 #######################################
 # EXAMPLE: readYesNoVar L2_SWITCH "y" "Are all nodes connected to a L2 switch? (entre y or n)" 1 30
 function readYesNoVar {
-  if [ "$1" == "" ]; then echo "-- readYesNoVar ERROR: arg 1 was not found" ; return 1; fi
-  if [ "$2" == "" ]; then echo "-- readYesNoVar ERROR: arg 2 was not found" ; return 1; fi
+  if [ "$1" == "" ]; then echo "-- readYesNoVar ERROR: arg 1 was not found" ; exit 1; fi
+  if [ "$2" == "" ]; then echo "-- readYesNoVar ERROR: arg 2 was not found" ; exit 1; fi
   # $1: Variable name
   # $2: Default value
   # $3: Message
@@ -99,8 +99,8 @@ function readYesNoVar {
 #######################################
 # EXAMPLE: NODE_ARRAY_DEFAULT="(10.99.0.100 10.99.0.101 10.99.0.102 10.99.0.103)" && readArrayVar NODE_ARRAY "Please entre kubernetes cluster's nodes IP addresses the first one is the master (separate IPs with SPACE)" "$(IFS=' ' ; echo "$NODE_ARRAY_DEFAULT" )"
 function readArrayVar {
-  if [ "$1" == "" ]; then echo "-- readArrayVar ERROR: arg 1 was not found" ; return 1; fi
-  if [ "$2" == "" ]; then echo "-- readArrayVar ERROR: arg 2 was not found" ; return 1; fi
+  if [ "$1" == "" ]; then echo "-- readArrayVar ERROR: arg 1 was not found" ; exit 1; fi
+  if [ "$2" == "" ]; then echo "-- readArrayVar ERROR: arg 2 was not found" ; exit 1; fi
   # $1: Variable name
   # $2: Message
   # $4: Default value
@@ -125,7 +125,7 @@ function readArrayVar {
 #######################################
 # EXAMPLE: NEXT_IP 192.168.1.99 1
 function NEXT_IP {
-  if [ "$1" == "" ]; then echo "-- NEXT_IP ERROR: arg 1 was not found" ; return 1; fi
+  if [ "$1" == "" ]; then echo "-- NEXT_IP ERROR: arg 1 was not found" ; exit 1; fi
   IP="$1"
   for ((i = 0; i <= "$2"; i++)); do
     # shellcheck disable=SC2183
@@ -141,7 +141,7 @@ function NEXT_IP {
 }
 
 # function NEXT_IP {
-#   if [ "$1" == "" ]; then echo "-- NEXT_IP ERROR: arg 1 was not found" ; return 1; fi
+#   if [ "$1" == "" ]; then echo "-- NEXT_IP ERROR: arg 1 was not found" ; exit 1; fi
 #   IP="$1"
 #   for ((i = 0; i <= "$2"; i++)); do
 #     IP_HEX=$(printf '%.2X%.2X%.2X%.2X\n' "$(echo "$IP" | sed -e 's/\./ /g')")
@@ -159,7 +159,7 @@ function NEXT_IP {
 # EXAMPLE: NODE_ARRAY="(10.99.0.100 10.99.0.101 10.99.0.102 10.99.0.103)" && WAIT_ALL_NODES_ONLINE $NODE_ARRAY
 function WAIT_ALL_NODES_ONLINE {
   # $1 Array of servers
-  if [ "$1" == "" ]; then echo "-- WAIT_ALL_NODES_ONLINE ERROR: arg 1 was not found" ; return 1; fi
+  if [ "$1" == "" ]; then echo "-- WAIT_ALL_NODES_ONLINE ERROR: arg 1 was not found" ; exit 1; fi
   NODE_ARRAY="$1"
   echo "-- Waiting for all nodes to be online"
   for ((i = 0; i <= ${#NODE_ARRAY[@]} - 1; i++)); do
@@ -180,7 +180,7 @@ function WAIT_ALL_NODES_ONLINE {
 # EXAMPLE: NODE_ARRAY="(10.99.0.100 10.99.0.101 10.99.0.102 10.99.0.103)" && IS_ALL_NODES_ONLINE $NODE_ARRAY
 function IS_ALL_NODES_ONLINE {
   # $1 Array of servers
-  if [ "$1" == "" ]; then echo "-- IS_ALL_NODES_ONLINE ERROR: arg 1 was not found" ; return 1; fi
+  if [ "$1" == "" ]; then echo "-- IS_ALL_NODES_ONLINE ERROR: arg 1 was not found" ; exit 1; fi
   export NODE_ARRAY="$1"
   echo "-- Checking if all nodes are online"
   if [[ -z $NODE_ARRAY ]]; then
@@ -206,8 +206,8 @@ function IS_ALL_NODES_ONLINE {
 function RESTART_ALL_NODES {
   # $1 Array of servers
   # $2 Private key path
-  if [ "$1" == "" ]; then echo "-- RESTART_ALL_NODES ERROR: arg 1 was not found" ; return 1; fi
-  if [ "$2" == "" ]; then echo "-- RESTART_ALL_NODES ERROR: arg 2 was not found" ; return 1; fi
+  if [ "$1" == "" ]; then echo "-- RESTART_ALL_NODES ERROR: arg 1 was not found" ; exit 1; fi
+  if [ "$2" == "" ]; then echo "-- RESTART_ALL_NODES ERROR: arg 2 was not found" ; exit 1; fi
   NODE_ARRAY="$1"
   PRIVATE_KEY="$2"
   for ((i = 1; i <= ${#NODE_ARRAY[@]} - 1; i++)); do
@@ -230,13 +230,10 @@ function RESTART_ALL_NODES {
 function SSH_COPY_ID {
   # $1 Array of servers
   # $2 Private key path
-  if [ "$1" == "" ]; then echo "-- SSH_COPY_ID ERROR: arg 1 was not found" ; return 1; fi
-  if [ "$2" == "" ]; then echo "-- SSH_COPY_ID ERROR: arg 2 was not found" ; return 1; fi
-
+  if [ "$1" == "" ]; then echo "-- SSH_COPY_ID ERROR: arg 1 was not found" ; exit 1; fi
+  if [ "$2" == "" ]; then echo "-- SSH_COPY_ID ERROR: arg 2 was not found" ; exit 1; fi
   NODE_ARRAY="$1"
   PRIVATE_KEY="$2"
-  if [ "$PRIVATE_KEY" == "" ]; then echo "-- ERROR: PRIVATE_KEY is empty " ; return 1; fi
-
   if [ ! -f "$PRIVATE_KEY" ]; then
     echo "-- $PRIVATE_KEY not found. Generating new keys"
     mkdir -p "$(dirname "$PRIVATE_KEY")"
