HOW TO

diff --git a/_include b/_include
--- a/_include
+++ b/_include
@@ -17,6 +17,8 @@
 # under the License.
 #
 # HOW TO:
+# rm -r scripts && git clone https://github.com/alrokayan/scripts.git && cd scripts && chmod +x * && ./
+# OR
 # source <(curl -sfL -H 'Cache-Control: no-cache, no-store' https://raw.githubusercontent.com/alrokayan/scripts/main/_include)
 #######################################
 #######################################
@@ -39,7 +41,7 @@ function readVar {
       read -r INPUT
     else
       echo ">> $3: (Default: ${!1}) [TIMEOUT: ${5}s]"
-      read -t $5 -r INPUT
+      read -t "$5" -r INPUT
     fi
     [[ $INPUT != "" ]] && eval "export $1=$INPUT"
   else
@@ -75,7 +77,7 @@ function readYesNoVar {
       fi
     else
       echo ">> $3: (Default: ${!1}) [TIMEOUT: ${5}s]"
-      read -t $5 -r INPUT
+      read -t "$5" -r INPUT
       if [[ "$INPUT" =~ "y" ]]; then
         INPUT="y"
       else
@@ -95,7 +97,7 @@ function readYesNoVar {
 ##### FUNCTION readArrayVar ###########
 #######################################
 #######################################
-# EXAMPLE: NODE_ARRAY_DEFAULT="(10.99.0.100 10.99.0.101 10.99.0.102 10.99.0.103)" && readArrayVar NODE_ARRAY "Please entre kubernetes cluster's nodes IP addresses the first one is the master (seperate IPs with SPACE)" "$(IFS=' ' ; echo "$NODE_ARRAY_DEFAULT" )"
+# EXAMPLE: NODE_ARRAY_DEFAULT="(10.99.0.100 10.99.0.101 10.99.0.102 10.99.0.103)" && readArrayVar NODE_ARRAY "Please entre kubernetes cluster's nodes IP addresses the first one is the master (separate IPs with SPACE)" "$(IFS=' ' ; echo "$NODE_ARRAY_DEFAULT" )"
 function readArrayVar {
   if [ "$1" == "" ]; then echo "-- readArrayVar ERROR: arg 1 was not found" ; return 1; fi
   if [ "$2" == "" ]; then echo "-- readArrayVar ERROR: arg 2 was not found" ; return 1; fi
@@ -114,7 +116,6 @@ function readArrayVar {
       echo "export $1=($3)" >>.env
     fi
   fi
-  . .env
 }
 
 #######################################
@@ -127,12 +128,23 @@ function NEXT_IP {
   if [ "$1" == "" ]; then echo "-- NEXT_IP ERROR: arg 1 was not found" ; return 1; fi
   IP="$1"
   for ((i = 0; i <= "$2"; i++)); do
-    IP_HEX=$(printf '%.2X%.2X%.2X%.2X\n' `echo $IP | sed -e 's/\./ /g'`)
-    NEXT_IP_HEX=$(printf %.8X `echo $(( 0x$IP_HEX + 1 ))`)
-    IP=$(printf '%d.%d.%d.%d\n' `echo $NEXT_IP_HEX | sed -r 's/(..)/0x\1 /g'`)
+    IP_HEX=$(printf '%.2X%.2X%.2X%.2X\n' "${IP//./ }")
+    NEXT_IP_HEX=$(printf %.8X "$(( 0x$IP_HEX + 1 ))")
+    IP=$(printf '%d.%d.%d.%d\n' "$(echo "$NEXT_IP_HEX" | sed -r 's/(..)/0x\1 /g')")
   done
   echo "$IP"
 }
+
+# function NEXT_IP {
+#   if [ "$1" == "" ]; then echo "-- NEXT_IP ERROR: arg 1 was not found" ; return 1; fi
+#   IP="$1"
+#   for ((i = 0; i <= "$2"; i++)); do
+#     IP_HEX=$(printf '%.2X%.2X%.2X%.2X\n' "$(echo "$IP" | sed -e 's/\./ /g')")
+#     NEXT_IP_HEX=$(printf %.8X "$(echo $(( 0x$IP_HEX + 1 )))")
+#     IP=$(printf '%d.%d.%d.%d\n' `echo $NEXT_IP_HEX | sed -r 's/(..)/0x\1 /g'`)
+#   done
+#   echo "$IP"
+# }
 
 #######################################
 #######################################
@@ -147,7 +159,7 @@ function WAIT_ALL_NODES_ONLINE {
   echo "-- Waiting for all nodes to be online"
   for ((i = 0; i <= ${#NODE_ARRAY[@]} - 1; i++)); do
     host="${NODE_ARRAY[$i]}"
-    while ! ping -c1 $host &>/dev/null; do
+    while ! ping -c1 "$host" &>/dev/null; do
       echo "-- Waiting for $host to be online"
       sleep 5
     done
@@ -195,13 +207,13 @@ function RESTART_ALL_NODES {
   PRIVATE_KEY="$2"
   for ((i = 1; i <= ${#NODE_ARRAY[@]} - 1; i++)); do
     echo "-- Rebooting ${NODE_ARRAY[$i]}"
-    (ssh -i "$PRIVATE_KEY" $SSH_EXTRA_ARGS "$SSH_USERNAME"@"${NODE_ARRAY[$i]}" "reboot") &
+    (ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"${NODE_ARRAY[$i]}" "reboot") &
   done
   wait
   echo "-- Rebooting ${NODE_ARRAY[0]}"
-  ssh -i "$PRIVATE_KEY" $SSH_EXTRA_ARGS "$SSH_USERNAME"@"${NODE_ARRAY[0]}" "reboot"
+  ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"${NODE_ARRAY[0]}" "reboot"
   sleep 10
-  WAIT_ALL_NODES_ONLINE $NODE_ARRAY
+  WAIT_ALL_NODES_ONLINE "$NODE_ARRAY"
 }
 
 #######################################
@@ -220,27 +232,27 @@ function SSH_COPY_ID {
   PRIVATE_KEY="$2"
   if [ "$PRIVATE_KEY" == "" ]; then echo "-- ERROR: PRIVATE_KEY is empty " ; return 1; fi
 
-  if [ ! -f $PRIVATE_KEY ]; then
+  if [ ! -f "$PRIVATE_KEY" ]; then
     echo "-- $PRIVATE_KEY not found. Generating new keys"
-    mkdir -p "$(dirname $PRIVATE_KEY)"
+    mkdir -p "$(dirname "$PRIVATE_KEY")"
     ssh-keygen -t rsa -b 4096 -C "k8s" -f "$PRIVATE_KEY" -N ""
   else
     echo "-- Using $PRIVATE_KEY"
   fi
-  chmod 700 "$(dirname $PRIVATE_KEY)"
+  chmod 700 "$(dirname "$PRIVATE_KEY")"
   chmod 600 "$PRIVATE_KEY"
   chmod 644 "$PRIVATE_KEY.pub"
   echo "PUBLIC KEY: "
   cat "$PRIVATE_KEY.pub"
 
-  WAIT_ALL_NODES_ONLINE $NODE_ARRAY
+  WAIT_ALL_NODES_ONLINE "$NODE_ARRAY"
   for ((i = 0; i <= ${#NODE_ARRAY[@]} - 1; i++)); do
     IP=${NODE_ARRAY[$i]}
     echo "-- copying public key to $IP "
     ssh-keygen -f "$HOME/.ssh/known_hosts" -R "$IP"
     mkdir -p ~/.ssh
     chmod 700 ~/.ssh
-    ssh-copy-id -o LogLevel=QUIET -i "$PRIVATE_KEY" $SSH_EXTRA_ARGS "$SSH_USERNAME"@"$IP" 1>&3
+    ssh-copy-id -o LogLevel=QUIET -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP" 1>&3
   done
   return 0
 }
